

-- STARTUP NOMOUNT
CREATE CONTROLFILE SET DATABASE "VISDEV" RESETLOGS  NOARCHIVELOG
    MAXLOGFILES 32
    MAXLOGMEMBERS 5
    MAXDATAFILES 512
    MAXINSTANCES 8
    MAXLOGHISTORY 1530
LOGFILE
  GROUP 1 '/d03/oracle/VISDEV/data/log3.dbf'  SIZE 300M BLOCKSIZE 512,
  GROUP 2 '/d03/oracle/VISDEV/data/log2.dbf'  SIZE 300M BLOCKSIZE 512,
  GROUP 3 '/d03/oracle/VISDEV/data/log1.dbf'  SIZE 300M BLOCKSIZE 512
-- STANDBY LOGFILE
DATAFILE
  '/d03/oracle/VISDEV/data/sys1.dbf',
  '/d03/oracle/VISDEV/data/sys2.dbf',
  '/d03/oracle/VISDEV/data/sys3.dbf',
  '/d03/oracle/VISDEV/data/sys4.dbf',
  '/d03/oracle/VISDEV/data/sys5.dbf',
  '/d03/oracle/VISDEV/data/sys6.dbf',
  '/d03/oracle/VISDEV/data/sys7.dbf',
  '/d03/oracle/VISDEV/data/sys8.dbf',
  '/d03/oracle/VISDEV/data/sys9.dbf',
  '/d03/oracle/VISDEV/data/sys10.dbf',
  '/d03/oracle/VISDEV/data/sys11.dbf',
  '/d03/oracle/VISDEV/data/sysaux01.dbf',
  '/d03/oracle/VISDEV/data/sysaux02.dbf',
  '/d03/oracle/VISDEV/data/system12.dbf',
  '/d03/oracle/VISDEV/data/system13.dbf',
  '/d03/oracle/VISDEV/data/system14.dbf',
  '/d03/oracle/VISDEV/data/undotbs001.dbf',
  '/d03/oracle/VISDEV/data/omo1.dbf',
  '/d03/oracle/VISDEV/data/archive1.dbf',
  '/d03/oracle/VISDEV/data/undotbs002.dbf',
  '/d03/oracle/VISDEV/data/undotbs003.dbf',
  '/d03/oracle/VISDEV/data/apps_ts_interface.dbf',
  '/d03/oracle/VISDEV/data/media1.dbf',
  '/d03/oracle/VISDEV/data/media2.dbf',
  '/d03/oracle/VISDEV/data/media3.dbf',
  '/d03/oracle/VISDEV/data/nologging1.dbf',
  '/d03/oracle/VISDEV/data/nologging3.dbf',
  '/d03/oracle/VISDEV/data/queues1.dbf',
  '/d03/oracle/VISDEV/data/queues2.dbf',
  '/d03/oracle/VISDEV/data/reference1.dbf',
  '/d03/oracle/VISDEV/data/reference2.dbf',
  '/d03/oracle/VISDEV/data/summary1.dbf',
  '/d03/oracle/VISDEV/data/summary2.dbf',
  '/d03/oracle/VISDEV/data/summary3.dbf',
  '/d03/oracle/VISDEV/data/summary4.dbf',
  '/d03/oracle/VISDEV/data/summary5.dbf',
  '/d03/oracle/VISDEV/data/summary6.dbf',
  '/d03/oracle/VISDEV/data/summary7.dbf',
  '/d03/oracle/VISDEV/data/tx_data1.dbf',
  '/d03/oracle/VISDEV/data/tx_data2.dbf',
  '/d03/oracle/VISDEV/data/tx_data3.dbf',
  '/d03/oracle/VISDEV/data/tx_data4.dbf',
  '/d03/oracle/VISDEV/data/tx_data5.dbf',
  '/d03/oracle/VISDEV/data/tx_data6.dbf',
  '/d03/oracle/VISDEV/data/tx_data7.dbf',
  '/d03/oracle/VISDEV/data/tx_data8.dbf',
  '/d03/oracle/VISDEV/data/tx_data9.dbf',
  '/d03/oracle/VISDEV/data/tx_data10.dbf',
  '/d03/oracle/VISDEV/data/tx_data11.dbf',
  '/d03/oracle/VISDEV/data/tx_data12.dbf',
  '/d03/oracle/VISDEV/data/tx_data13.dbf',
  '/d03/oracle/VISDEV/data/tx_data14.dbf',
  '/d03/oracle/VISDEV/data/tx_data15.dbf',
  '/d03/oracle/VISDEV/data/tx_data16.dbf',
  '/d03/oracle/VISDEV/data/tx_data17.dbf',
  '/d03/oracle/VISDEV/data/tx_data18.dbf',
  '/d03/oracle/VISDEV/data/tx_data19.dbf',
  '/d03/oracle/VISDEV/data/tx_data20.dbf',
  '/d03/oracle/VISDEV/data/tx_data21.dbf',
  '/d03/oracle/VISDEV/data/tx_data22.dbf',
  '/d03/oracle/VISDEV/data/tx_data23.dbf',
  '/d03/oracle/VISDEV/data/tx_data24.dbf',
  '/d03/oracle/VISDEV/data/tx_data25.dbf',
  '/d03/oracle/VISDEV/data/tx_data26.dbf',
  '/d03/oracle/VISDEV/data/tx_data27.dbf',
  '/d03/oracle/VISDEV/data/tx_idx1.dbf',
  '/d03/oracle/VISDEV/data/tx_idx2.dbf',
  '/d03/oracle/VISDEV/data/tx_idx3.dbf',
  '/d03/oracle/VISDEV/data/tx_idx4.dbf',
  '/d03/oracle/VISDEV/data/tx_idx5.dbf',
  '/d03/oracle/VISDEV/data/tx_idx6.dbf',
  '/d03/oracle/VISDEV/data/tx_idx7.dbf',
  '/d03/oracle/VISDEV/data/tx_idx8.dbf',
  '/d03/oracle/VISDEV/data/tx_idx9.dbf',
  '/d03/oracle/VISDEV/data/tx_idx10.dbf',
  '/d03/oracle/VISDEV/data/tx_idx11.dbf',
  '/d03/oracle/VISDEV/data/tx_idx12.dbf',
  '/d03/oracle/VISDEV/data/tx_idx13.dbf',
  '/d03/oracle/VISDEV/data/tx_idx14.dbf',
  '/d03/oracle/VISDEV/data/tx_idx15.dbf',
  '/d03/oracle/VISDEV/data/tx_idx16.dbf',
  '/d03/oracle/VISDEV/data/tx_idx17.dbf',
  '/d03/oracle/VISDEV/data/tx_idx18.dbf',
  '/d03/oracle/VISDEV/data/tx_idx19.dbf',
  '/d03/oracle/VISDEV/data/tx_idx20.dbf',
  '/d03/oracle/VISDEV/data/tx_idx21.dbf',
  '/d03/oracle/VISDEV/data/system15.dbf',
  '/d03/oracle/VISDEV/data/system16.dbf',
  '/d03/oracle/VISDEV/data/system17.dbf',
  '/d03/oracle/VISDEV/data/system18.dbf',
  '/d03/oracle/VISDEV/data/system19.dbf',
  '/d03/oracle/VISDEV/data/system20.dbf',
  '/d03/oracle/VISDEV/data/ctx1.dbf',
  '/d03/oracle/VISDEV/data/a_ref03.dbf',
  '/d03/oracle/VISDEV/data/dcm.dbf',
  '/d03/oracle/VISDEV/data/a_ref04.dbf',
  '/d03/oracle/VISDEV/data/a_ref05.dbf',
  '/d03/oracle/VISDEV/data/dm_olaptrain_arc.dbf',
  '/d03/oracle/VISDEV/data/opmtr01.dbf',
  '/d03/oracle/VISDEV/data/odm.dbf',
  '/d03/oracle/VISDEV/data/owb1.dbf',
  '/d03/oracle/VISDEV/data/owb2.dbf',
  '/d03/oracle/VISDEV/data/xdb01.dbf'
CHARACTER SET AL32UTF8
/
